import { z } from 'zod';

// UI Component Protocol Definition
// This schema defines the structure of dynamic UI components generated by the AI

// Define schemas individually for clearer separation and reusability
export const ExplanationSchema = z.object({
  type: z.literal('explanation'),
  title: z.string().optional().describe('Short title for the section'),
  content: z.string().describe('Markdown content explaining the concept'),
  tone: z.enum(['neutral', 'encouraging', 'simple', 'detailed']).default('neutral'),
});

export const QuizSchema = z.object({
  type: z.literal('quiz'),
  question: z.string().describe('The question text'),
  options: z.array(z.string()).min(2).describe('List of possible answers'),
  correctIndex: z.number().int().min(0).describe('Index of the correct answer (0-based)'),
  explanation: z.string().describe('Explanation of why the answer is correct'),
  difficulty: z.enum(['easy', 'medium', 'hard']),
});

export const CodeSchema = z.object({
  type: z.literal('code'),
  language: z.string().default('typescript'),
  description: z.string().describe('Instructions for the coding task'),
  starterCode: z.string().describe('Initial code with TODOs or blanks. MUST be actual code, not a question.'),
  solution: z.string().describe('Complete working solution code'),
  hints: z.array(z.string()).optional(),
});

export const ConfidenceCheckSchema = z.object({
  type: z.literal('confidence_check'),
  question: z.string().default('Do you feel confident about this concept?'),
  minLabel: z.string().default('Not at all'),
  maxLabel: z.string().default('Fully understood'),
});

export const ConceptMapSchema = z.object({
  type: z.literal('concept_map'),
  nodes: z.array(z.object({
    id: z.string(),
    label: z.string(),
    type: z.enum(['concept', 'example', 'category']).default('concept')
  })),
  edges: z.array(z.object({
    from: z.string(),
    to: z.string(),
    label: z.string().optional()
  }))
});

export const UIComponentSchema = z.discriminatedUnion('type', [
  ExplanationSchema,
  QuizSchema,
  CodeSchema,
  ConfidenceCheckSchema,
  ConceptMapSchema
]);

// The overall response from the AI agent
export const LearningResponseSchema = z.object({
  // The AI's internal reasoning for the current decision
  reasoning: z.string().describe('Brief explanation of why this module was chosen based on user state'),
  
  // The primary UI component to render
  ui: UIComponentSchema,
  
  // Suggested follow-up actions (chips/buttons)
  suggestedActions: z.array(z.object({
    label: z.string(),
    action: z.string().describe('The value to send back when clicked'),
    type: z.enum(['primary', 'secondary', 'danger']).default('secondary')
  })).optional()
});

export type UIComponent = z.infer<typeof UIComponentSchema>;
export type LearningResponse = z.infer<typeof LearningResponseSchema>;
